#+TITLE: Introduction au Guide de Déploiement
#+AUTHOR: OLPC Foundation (c) 2011 One Laptop Per Child Association, Inc.
#+DATE: 2011-09-12
#+OPTIONS: toc:nil

[[file:index.org][Table des matières]] -- [[file:theindex.org][Index]]

* Introduction

Ce guide détaille les instructions aux chefs de projet (tels qu'officiels
gouvernementaux, fondations, fonds privés, etc.) qui dirigent des
déploiements OLPC à grande échelle (écoles, villes, régions et pays).

Fort du savoir et de l'expertise de déploiements de plus de deux millions
d'ordinateurs portables et dans plus de trente pays, il indique quels sont
les facteurs-clé au cours des différentes étapes d'un déploiement. Il peut
être adapté à chaque nouveau déploiement selon le contexte culturel,
économique et socio-politique du pays concerné.

* Vue d'ensemble des phases de déploiement

Un déploiement se compose de trois étapes principales : planification,
déploiement, post-déploiement. Ce document a pour but de guider les chefs
de projet depuis leur feuille de route jusqu'à la réussite du déploiement
par la description des points essentiels, des prises de décision et par la
chronologie des actions.

[[file:index.org][Table des matières]] -- [[file:theindex.org][Index]]
