#+TITLE: Stratégie d'apprentissage
#+AUTHOR: OLPC Foundation (c) 2011 One Laptop Per Child Association, Inc.
#+DATE: 2011-09-12
#+OPTIONS: toc:nil

#+HTML: <div class="menu">
- [[file:olpc-deployment-guide-one-laptop-per-child.org][One Laptop Per Child]]
- [[file:index.org][Table des matières]]
- [[file:olpc-deployment-guide-introduction-au-guide-de-deploiement.org][Introduction au guide de déploiement]]
#+HTML: </div>

#+index: Apprentissage
#+index: Seymour Papert
#+index: Jean Piaget

« Il s'agit d'un projet éducatif et non d'un projet informatique. » 

Nos principes sont basés sur la théorie du constructionnisme ; celle-ci se
réfère à la théorie de « l'apprentissage par l'action ». Son auteur en est
Seymour Papert, mathématicien, informaticien et éducateur ; celle-ci est
elle-même basée sur les théories d'apprentissage constructivistes du
psychologue suisse Jean Piaget.

Papert pense que l'apprentissage est plus efficace lorsque l'élève est
lui-même engagé dans le processus ; il pense aussi que la technologie est
un outil aidant à la construction de ce savoir. C'est à lui que l'on doit
les pas les plus importants pour amener les enfants à contrôler ces
nouvelles technologies. Par ses recherches et leurs conclusions, il propose
que les enfants eux-mêmes apprennent à programmer afin de développer les
compétences uniques qui les amèneront à comprendre la façon dont ils
apprennent. 

Notre philosophie s'inspire des travaux de Papert et d'autres éducateurs
progressistes ayant les mêmes concepts sur l'apprentissage. Nous pensons
que le XO amène les enfants à développer leur savoir à partir de leurs
intérêts personnels parce qu'il leur fournit des outils qui sont aptes à
leur faire partager et critiquer cette construction de savoir, ce qui les
amène à devenir de meilleurs étudiants et de meilleurs enseignants. De
plus, bien que notre objectif premier ne soit pas la compétence en
informatique, elle se développe facilement par elle-même au fur et à mesure
que les enfants s'approprient leurs XO pendant leur apprentissage. 

Notre stratégie d'apprentissage se focalise sur la construction :

- en développant l'aisance digitale ; celle-ci se réfère aux outils de
  programmation informatique et à l'habileté d'élaborer des objets censés
  grâce aux outils technologiques. « Une personne technologiquement à
  l'aise devrait aller du germe d'une intuition à la mise en oeuvre d'un
  projet technologique (Papert & Resnick, 1995) ».

- en réfléchissant à l'apprentissage : comment apprend-on à apprendre ?
  Comment réfléchit-on sur ses propres stratégies d'apprentissage ?

- en misant sur un apprentissage et de nouvelles compétences basés sur les
  valeurs du XXIe siècle :

  - Créativité et innovation 
  - Pensée critique et résolution de problèmes 
  - Communication et collaboration 

*Logiciel : La plateforme d'apprentissage Sugar*

#+index: Sugar
#+index: Constructionnisme


Basés sur le constructionnisme et en accord avec nos principes sur les
logiciels libres, nous avons créé Sugar, la plateforme la plus appropriée
pour concrétiser ces stratégies d'apprentissage. Avec les activités
proposées par Sugar, les enfants découvrent une manière d'explorer des
connaissances à travers différents medias et outils de programmation. Sugar
met en avant l'apprentissage collaboratif au travers d'activités
encourageant la pensée critique, la collaboration et la réflexion.

#+HTML: <div class="menu">

- [[file:olpc-deployment-guide-one-laptop-per-child.org][One Laptop Per Child]]
- [[file:index.org][Table des matières]]
- [[file:olpc-deployment-guide-introduction-au-guide-de-deploiement.org][Introduction au guide de déploiement]]

#+HTML: </div>
