#+TITLE: Introduction au Guide de Déploiement
#+AUTHOR: OLPC Foundation (c) 2011 One Laptop Per Child Association, Inc.
#+DATE: 2011-09-12
#+OPTIONS: toc:nil

#+HTML: <div class="menu">
- [[file:olpc-deployment-guide-liens-utiles.org][Liens utiles]]
- [[file:index.org][Table des matières]]
- [[file:theindex.org][Index]]
#+HTML: </div>

* Licence

Ce document est sous licence Creative Commons [[http://creativecommons.org/licenses/by/3.0/][CC BY 3.0]].  Il est permis à
quiconque d'utiliser ce document et d'en produire des versions dérivées
tant que la source et l'auteur original (One Laptop Per Child) sont cités.

* Versions

La version anglaise de ce document est disponible [[http://wiki.laptop.org/images/1/1c/OLPC_Deployment_Guide_2011.pdf][au format PDF]] et [[http://wiki.laptop.org/go/Deployment_Guide_2011][en
version Wiki]] sur le site d'OLPC.

Les sources pour la traduction sont disponibles via [[https://github.com/bzg/OLPC-Deployment--community--guide][ce dépôt git]], qui
contient le fichier original (PDF), une version en [[http://fr.wikipedia.org/wiki/OpenDocument][Open Document Format]] et
une version texte utilisant le format [[http://orgmode.org][Org-mode]].  Les conversions en =.odt=
=HTML= et =PDF= ont été effectuées via org-mode.

Le site d'OLPC France héberge [[http://olpc-france.org/guide-deploiement/olpc-guide-deploiement.pdf][une version PDF]] et une [[http://olpc-france.org/guide-deploiement/olpc-guide-deploiement.html][version HTML]].  Il
existe aussi une [[http://olpc-france.org/guide-deploiement/index.html][version en ligne]] que nous vous engageons à /commenter/:
posez-y toutes les questions que vous avez sur les déploiments OLPC ou 
sur le guide lui-même, OLPC France essaiera d'y répondre.

* Crédits

La traduction française a été faite par OLPC France entre septembre et
novembre 2011.  Merci aux membres d'OLPC France qui y ont contribué :

- Cécile Wyler Roulet
- Kévin Raymond
- Pierre Varly
- Samy Boutayeb
- Bastien Guerry

#+HTML: <div class="menu">
- [[file:olpc-deployment-guide-liens-utiles.org][Liens utiles]]
- [[file:index.org][Table des matières]]
- [[file:theindex.org][Index]]
#+HTML: </div>
