#+TITLE: Stratégie de support
#+AUTHOR: OLPC Foundation (c) 2011 One Laptop Per Child Association, Inc.
#+DATE: 2011-09-12
#+OPTIONS: toc:nil

#+HTML: <div class="menu">

- [[file:olpc-deployment-guide-phase-planification.org][Phase de planification]]
- [[file:index.org][Table des matières]]
- [[file:olpc-deployment-guide-realisation-projet.org][Mise en oeuvre du projet]]

#+HTML: </div>

#+index: Assistance
#+index: Support!Strategie

OLPC apporte un soutien durant les étapes du déploiement, tout
particulièrement dans les domaines opérationnel, éducatif et technique (qui
sont les plus importants). 

Pour que la maîtrise du déploiement soit locale et qu'il soit autonome,
nous aidons à créer et stimuler des compétences dans les domaines technique
et éducatif, en apportant à l'équipe principale la formation nécessaire
durant le prédéploiement puis une assistance à distance (courriel,
téléphone ou chat) durant le postdéploiement, et ceci selon les besoins du
projet. 

Ce support est gratuit (quelle que soit la taille du projet). Pour ceux de
25.000 unités et plus, une équipe OLPC éducative et technique se rend dans
le pays du déploiement et y assure une formation complète d'une
semaine. Ceci est aussi valable pour de plus petits projets (5.000 unités
et +) montrant un fort potentiel de croissance à court terme. Pour ceux de
plus de 50.000 unités, la formation initiale peut être étendue à deux
semaines et comporter deux sessions supplémentaires d'une semaine chacune
sur une période d'un an. 

Des visites ponctuelles pour un suivi sur place peuvent être faites sur
demande ; une formation éducative complémentaire à la formation initiale
peut être apportée 2-3 fois par an. Nous prenons en charge ces coûts de
formation sur place (à l'exception du matériel et des fournitures), même si
en général, les sponsors fournissent un logement approprié à l'équipe
OLPC. Dans des environnements très difficiles, nous pouvons envoyer une
équipe à plein temps comprenant le chef de projet et les directeurs
technique et éducatif. Le coût de ce type de service OLPC est à négocier
lors de la demande.

* Support opérationnel

Durant la phase de planification du déploiement et lorsque des décisions
stratégiques sont à prendre (concernant le financement, les contrats et le
processus de commande), nous apportons un support direct au chef de projet
et aux sponsors ainsi qu'un support logistique à la chaîne
d'approvisionnement. 

* Support éducatif

#+index: Dévelopement!Educatif

Lorsqu'un projet est officiellement implanté, nous proposons des ateliers
aux équipes principales afin qu'elles soient à même de mieux appréhender le
XO comme outil d'apprentissage. Durant la phase de structuration, nous
apportons des conseils aux écoles ou centres d'enseignement. Finalement, un
support continu sur le déploiement et le contenu éducatif est amené à
travers les différentes phases de formation aux enseignants par OLPC.

* Support technique

#+index: Support!Technique
#+index: Dévelopement!Technique

Nous nous concentrons aussi sur la création et la stimulation des capacités
locales comme la mise en oeuvre d'une infrastructure, la connectivité et
tout autre impératif concernant les logiciels, le matériel, la maintenance
et la réparation des XO.

* Support par des volontaires et des stagiaires

#+index: Volontaires
#+index: Stagiaires

Durant les mois de juin, juillet et août, nous proposons des stages aux
étudiants de grandes universités de plusieurs pays, le but étant de leur
permettre de travailler main dans la main avec l'équipe principale selon
leur formation et leur domaine d'étude.

#+HTML: <div class="menu">

- [[file:olpc-deployment-guide-phase-planification.org][Phase de planification]]
- [[file:olpc-deployment-guide-realisation-projet.org][Mise en oeuvre du projet]]
- [[file:index.org][Table des matières]]

#+HTML: </div>
